/**
 * Renders a Dockerfile from a (validated) WorkerImageSpec. Corral owns the skeleton:
 * the spec contributes the base image + project toolchain, and we ALWAYS append the
 * guaranteed runtime layer (git, Node, the agent CLIs, a non-root `worker`). The
 * spec's fields are validated so a malformed/hostile value can't inject extra
 * Dockerfile directives — the arbitrary part (setup_commands) is single-line only
 * and surfaced for human approval before any build.
 */
import type { WorkerImageSpec } from './spec.js';

/** The baseline CLI, always installed when no provider set is given (default primary). */
export const DEFAULT_AGENT_CLI = '@anthropic-ai/claude-code';

/** npm package providing each provider's CLI (the binary the transport spawns). */
export const AGENT_CLI_PACKAGES: Record<string, string> = {
  claude: DEFAULT_AGENT_CLI,
  gemini: '@google/gemini-cli',
};

export interface RenderDockerfileOptions {
  /** npm packages (CLIs) to install globally — one per configured agent provider.
   *  Empty/omitted → just the Claude CLI (the default primary). */
  agentClis?: string[];
}

/** npm package name (scoped or plain, no versions/flags/shell metachars). */
function assertSafePackageName(pkg: string): void {
  if (!/^(@[A-Za-z0-9._-]+\/)?[A-Za-z0-9._-]+$/.test(pkg)) {
    throw new Error(`unsafe npm package name: ${JSON.stringify(pkg)}`);
  }
}

/** Docker image reference: registry/namespace/name[:tag][@digest], no shell metachars. */
function assertSafeImageRef(ref: string): void {
  if (!/^[A-Za-z0-9][A-Za-z0-9._:/@-]*$/.test(ref)) {
    throw new Error(`unsafe base image reference: ${JSON.stringify(ref)}`);
  }
}

/** apt package name (no versions, flags, or shell metachars). */
function assertSafePackage(pkg: string): void {
  if (!/^[A-Za-z0-9][A-Za-z0-9.+-]*$/.test(pkg)) {
    throw new Error(`unsafe apt package name: ${JSON.stringify(pkg)}`);
  }
}

/** A RUN command must be a single line (no newline → no injected directives). */
function assertSingleLine(cmd: string): void {
  if (/[\r\n\0]/.test(cmd)) throw new Error(`setup command must be a single line: ${JSON.stringify(cmd)}`);
}

export function renderDockerfile(spec: WorkerImageSpec, opts: RenderDockerfileOptions = {}): string {
  assertSafeImageRef(spec.base_image);
  spec.system_packages.forEach(assertSafePackage);
  spec.setup_commands.forEach(assertSingleLine);

  // Install the CLI for every configured agent provider (primary + fallbacks) so
  // cross-provider failover works in the container, not just the primary's CLI.
  const cliPkgs = opts.agentClis?.length ? opts.agentClis : [DEFAULT_AGENT_CLI];
  cliPkgs.forEach(assertSafePackageName);

  const lines: string[] = [
    '# Generated by Corral — auto worker image. Review before building.',
    `FROM ${spec.base_image}`,
    'ENV DEBIAN_FRONTEND=noninteractive',
  ];

  if (spec.system_packages.length) {
    lines.push(
      'RUN apt-get update && apt-get install -y --no-install-recommends \\',
      `      ${spec.system_packages.join(' ')} \\`,
      '    && rm -rf /var/lib/apt/lists/*',
    );
  }
  for (const cmd of spec.setup_commands) lines.push(`RUN ${cmd}`);

  // ── Corral-guaranteed runtime (independent of the spec) ──
  lines.push(
    '# ── Corral runtime (guaranteed) ──',
    'RUN apt-get update && apt-get install -y --no-install-recommends git curl ca-certificates \\',
    '    && rm -rf /var/lib/apt/lists/*',
    'RUN command -v node >/dev/null 2>&1 || (curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && apt-get install -y nodejs)',
    `RUN npm install -g ${cliPkgs.join(' ')}`,
    // claude refuses --dangerously-skip-permissions as root, so run as a non-root user.
    'RUN useradd -m -s /bin/bash worker && mkdir -p /workspace && chown -R worker:worker /workspace',
    'USER worker',
    'WORKDIR /workspace',
    // The worker user has no git identity; `git commit` errors without one. The host
    // (local backend) inherits the operator's ~/.gitconfig, but a fresh container does
    // not — set a default so the agent can commit. safe.directory '*' avoids "dubious
    // ownership" if a repo dir ends up owned differently than the runner.
    'RUN git config --global user.email "agent@corral.local" \\',
    '    && git config --global user.name "Corral Agent" \\',
    '    && git config --global init.defaultBranch main \\',
    "    && git config --global --add safe.directory '*'",
  );

  return `${lines.join('\n')}\n`;
}
