/**
 * The wizard renders a whole config from the fields it models, so anything it does not
 * model was erased by every save. These are the blocks that now survive it, and the line
 * where preservation deliberately stops.
 */
import { describe, expect, it } from 'vitest';
import YAML from 'yaml';
import { mergePreserved, PRESERVED_BLOCKS } from './merge.js';

/** What the wizard writes: whole top-level blocks, and never the preserved ones. */
const FROM_WIZARD = `# Generated by the Corral setup wizard.
profile:
  language: "ko"
tracker:
  kind: notion
agent:
  provider: claude
workspace:
  backend: docker
channel:
  kind: web

max_active_issues: 3
`;

describe('what a save keeps', () => {
  it('carries over a block the wizard never writes', () => {
    const onDisk = `${FROM_WIZARD}\nreview:\n  rounds: 3\n`;

    const merged = mergePreserved(FROM_WIZARD, onDisk);

    expect(YAML.parse(merged)).toMatchObject({ review: { rounds: 3 }, max_active_issues: 3 });
  });

  it("leaves the wizard's own text alone, header and all", () => {
    // Appended rather than re-serialised: rewriting the whole document would change
    // formatting nobody asked to change, and lose the header comment.
    const merged = mergePreserved(FROM_WIZARD, `${FROM_WIZARD}\ncontrol_plane:\n  port: 4410\n`);

    expect(merged.startsWith(FROM_WIZARD.trimEnd())).toBe(true);
    expect(merged).toContain('# Generated by the Corral setup wizard.');
  });

  it('lets the wizard overwrite a block it does write', () => {
    // `max_active_issues` is the wizard's. The old value must not come back.
    const merged = mergePreserved(FROM_WIZARD, FROM_WIZARD.replace('max_active_issues: 3', 'max_active_issues: 9'));

    expect(YAML.parse(merged)).toMatchObject({ max_active_issues: 3 });
  });

  it('does not reach inside a block the wizard wrote', () => {
    // This is the line, and it is deliberate. Clearing a field works by not writing it —
    // an empty reference repo, a tracker with no scope property — so filling those back
    // in from the old file would make them impossible to clear. A setting that has to
    // survive gets modelled by the wizard instead; `limits` and the docker caps are.
    const onDisk = FROM_WIZARD.replace('  provider: claude', '  provider: claude\n  max_turns: 40');

    expect(YAML.parse(mergePreserved(FROM_WIZARD, onDisk)).agent).toEqual({ provider: 'claude' });
  });

  it('is a no-op on a first save', () => {
    expect(mergePreserved(FROM_WIZARD, null)).toBe(FROM_WIZARD);
  });

  it('writes anyway when the old file cannot be read', () => {
    // A save path. Refusing because the previous config was corrupt would trap someone
    // in a broken config with no way to replace it.
    expect(mergePreserved(FROM_WIZARD, 'this: [is not: yaml')).toBe(FROM_WIZARD);
  });

  it('names every block it keeps', () => {
    // The list is the answer to "what does saving overwrite?", so it is worth asserting
    // that it is a list and not an accident.
    expect([...PRESERVED_BLOCKS]).toEqual(['control_plane', 'review', 'plan_review', 'spec_mode']);
  });

  /**
   * Not a block but a scalar, and the reason it has to be here is the same: the wizard
   * renders the whole document from the fields it models, so turning spec-driven planning
   * on and then editing anything in the wizard would silently turn it back off (CRL-104).
   */
  it('keeps spec_mode through a wizard save', () => {
    const merged = mergePreserved(FROM_WIZARD, `${FROM_WIZARD}\nspec_mode: split\n`);
    expect(merged).toContain('spec_mode: split');
  });

  it('does not resurrect spec_mode when the incoming document sets it', () => {
    // Turning it back off has to work — a merge that always carried the old value would
    // make the setting one-way.
    const merged = mergePreserved(`${FROM_WIZARD}\nspec_mode: single\n`, `${FROM_WIZARD}\nspec_mode: split\n`);
    expect(merged).toContain('spec_mode: single');
    expect(merged).not.toContain('spec_mode: split');
  });
});
