/**
 * Collect the licenses of everything a distributed build carries, into one file.
 *
 * ## Why this exists
 * `NOTICE` used to promise a consolidated attribution list and point at an "Open source
 * licenses" screen. Neither existed, which is worse than saying nothing: a reader checking
 * compliance follows the pointer and finds air. The obligation is real — the build ships
 * `node_modules` as a resource, and MIT/ISC ask that their text and copyright travel with
 * a binary distribution (CRL-118).
 *
 * ## Why the output is committed
 * A license reviewer reads the repository, not a `.dmg`. Keeping the generated file in the
 * tree means the claim can be checked without building anything, and `--check` makes a
 * stale file a build failure rather than a silent lie.
 *
 * ## Why no dependency does this
 * There are good license-scanner packages. Adding one would put a tool in the tree whose
 * own attribution we would then have to carry, to solve attribution. Node built-ins and
 * `pnpm list` are enough: pnpm is already required (`only-allow pnpm`), and it is the only
 * thing that knows which packages are *production* and where they actually live.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'THIRD-PARTY-LICENSES.txt');

/** Workspaces whose *production* trees end up in the build. */
const WORKSPACES = [
  { name: 'core', dir: ROOT },
  { name: 'desktop', dir: join(ROOT, 'desktop') },
];

/** Filenames a package might keep its license text in. Matched case-insensitively. */
const LICENSE_FILES = /^(licen[cs]e|copying|notice)(\.(md|txt|markdown))?$/i;

/** Ask pnpm for one workspace's production tree, flattened to name@version → path. */
function productionTree(dir) {
  const raw = execFileSync('pnpm', ['list', '--prod', '--depth', 'Infinity', '--json'], {
    cwd: dir,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  });
  const found = new Map();
  const walk = (deps) => {
    for (const [name, info] of Object.entries(deps ?? {})) {
      const key = `${name}@${info.version}`;
      if (!found.has(key) && info.path) found.set(key, info.path);
      walk(info.dependencies);
    }
  };
  for (const project of JSON.parse(raw)) walk(project.dependencies);
  // An empty tree means the install is incomplete, not that nothing is bundled. Producing a
  // short list quietly is the exact failure this file is meant to prevent, so stop instead.
  if (found.size === 0) {
    throw new Error(`no production dependencies resolved in ${dir} — run \`pnpm install\` first`);
  }
  return found;
}

/** The license text as the package itself ships it — not a guess from an SPDX id. */
function licenseText(pkgPath) {
  if (!existsSync(pkgPath)) return undefined;
  for (const entry of readdirSync(pkgPath).sort()) {
    if (LICENSE_FILES.test(entry)) {
      const body = readFileSync(join(pkgPath, entry), 'utf8').trim();
      if (body) return { file: entry, body };
    }
  }
  return undefined;
}

function declaredLicense(manifest) {
  const l = manifest.license ?? manifest.licenses;
  if (typeof l === 'string') return l;
  if (Array.isArray(l)) return l.map((x) => x.type ?? x).join(' OR ');
  if (l && typeof l === 'object') return l.type ?? '(unknown)';
  return '(none declared)';
}

const packages = new Map();
for (const ws of WORKSPACES) {
  for (const [key, path] of productionTree(ws.dir)) {
    const existing = packages.get(key);
    if (existing) {
      existing.usedBy.add(ws.name);
      continue;
    }
    const manifestPath = join(path, 'package.json');
    if (!existsSync(manifestPath)) continue;
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
    packages.set(key, {
      key,
      name: manifest.name ?? key,
      version: manifest.version ?? '',
      license: declaredLicense(manifest),
      text: licenseText(path),
      usedBy: new Set([ws.name]),
    });
  }
}

const sorted = [...packages.values()].sort((a, b) => a.key.localeCompare(b.key));

// A package whose text cannot be found is the one case that must not pass quietly — the
// whole point is that nothing is omitted without someone deciding to omit it.
const missing = sorted.filter((p) => !p.text);

const lines = [
  'Third-party licenses',
  '====================',
  '',
  'Corral itself is Apache-2.0 (see LICENSE and NOTICE). This file lists the',
  'third-party packages a distributed build carries, with the license text each',
  'one ships. It is generated by `scripts/licenses.mjs` from the production',
  'dependency trees of the core and the desktop app — run `pnpm licenses` to',
  'regenerate, and `pnpm licenses:check` to fail if it is out of date.',
  '',
  `Packages: ${sorted.length}`,
  '',
];

for (const p of sorted) {
  lines.push(`  ${p.key}  —  ${p.license}  (${[...p.usedBy].sort().join(', ')})`);
}
lines.push('');

for (const p of sorted) {
  lines.push(
    '',
    '-'.repeat(78),
    `${p.name} ${p.version}`,
    `License: ${p.license}`,
    '-'.repeat(78),
    '',
    p.text ? p.text.body : '(no license file ships with this package; see its package.json)',
    '',
  );
}

const body = lines.join('\n');

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== body) {
    console.error('THIRD-PARTY-LICENSES.txt is out of date — run `pnpm licenses`.');
    process.exit(1);
  }
  console.log(`THIRD-PARTY-LICENSES.txt is current (${sorted.length} packages).`);
} else {
  writeFileSync(OUT, body, 'utf8');
  console.log(`wrote THIRD-PARTY-LICENSES.txt — ${sorted.length} packages`);
}

if (missing.length) {
  console.warn(`no license file found for: ${missing.map((p) => p.key).join(', ')}`);
}
