/** Setup-wizard state → corral.yaml + the secret writes. Secrets never go into the
 * config — only CredentialRef pointers do. The tracker is pluggable; Notion is one
 * option, GitHub Issues another. */

export type TrackerKind = 'notion' | 'github_issues';

export interface WizardState {
  // AI
  provider: 'claude' | 'gemini' | 'gpt';
  transport: 'api' | 'cli';
  agentKey: string;
  planningModel: string;
  implementationModel: string;
  // Repository (work repo)
  repo: string;
  repoKey: string;
  production: string;
  development: string;
  githubToken: string;
  // Tracker
  trackerKind: TrackerKind;
  // Tracker: Notion
  notionDb: string;
  notionToken: string;
  statusProp: string;
  idProp: string;
  repoProp: string;
  scopeProp: string;
  // Tracker: GitHub Issues
  issuesRepo: string; // blank → use the work repo
  scopeLabel: string;
  identifierPrefix: string;
  // shared: semantic state → tracker value (Notion status name OR GitHub label)
  states: { planning: string; plan_review: string; in_progress: string; in_review: string; done: string };
  // Workspace
  backend: 'local' | 'docker';
  // Channel / budget / profile
  port: number;
  maxActive: number;
  language: string;
  stack: string;
}

export function initialState(): WizardState {
  return {
    provider: 'claude',
    transport: 'cli',
    agentKey: '',
    planningModel: 'opus',
    implementationModel: 'sonnet',
    repo: '',
    repoKey: 'main',
    production: 'main',
    development: 'develop',
    githubToken: '',
    trackerKind: 'notion',
    notionDb: '',
    notionToken: '',
    statusProp: 'Status',
    idProp: 'ID',
    repoProp: '',
    scopeProp: '',
    issuesRepo: '',
    scopeLabel: 'corral',
    identifierPrefix: 'issue-',
    states: { planning: '', plan_review: '', in_progress: '', in_review: '', done: '' },
    backend: 'local',
    port: 4400,
    maxActive: 3,
    language: 'en',
    stack: 'generic',
  };
}

export function serviceFor(provider: WizardState['provider']): string {
  return { claude: 'anthropic', gemini: 'google', gpt: 'openai' }[provider];
}

const OWNER_NAME = /^[^/\s]+\/[^/\s]+$/;

/** Per-step validation → error string (empty = valid). Steps: 0..4. */
export function validateStep(step: number, s: WizardState): string {
  switch (step) {
    case 0:
      if (s.transport === 'api' && !s.agentKey.trim()) return 'API key is required for the api transport.';
      return '';
    case 1:
      if (!OWNER_NAME.test(s.repo)) return 'Repository must be "owner/name".';
      if (!s.githubToken.trim()) return 'A GitHub token is required.';
      if (!s.repoKey.trim()) return 'A routing key is required.';
      return '';
    case 2:
      for (const [k, v] of Object.entries(s.states)) if (!v.trim()) return `State mapping "${k}" is required.`;
      if (s.trackerKind === 'notion') {
        if (!s.notionDb.trim()) return 'Notion database id is required.';
        if (!s.notionToken.trim()) return 'A Notion token is required.';
        if (!s.statusProp.trim() || !s.idProp.trim()) return 'Status and ID property names are required.';
      } else {
        const repo = s.issuesRepo.trim() || s.repo.trim();
        if (!OWNER_NAME.test(repo)) return 'Issues repo must be "owner/name".';
      }
      return '';
    case 3:
      return '';
    case 4:
      if (!Number.isInteger(s.port) || s.port <= 0) return 'Port must be a positive integer.';
      return '';
    default:
      return '';
  }
}

function yamlStr(v: string): string {
  return JSON.stringify(v); // valid YAML, handles quoting/escaping
}

function trackerYaml(s: WizardState): string[] {
  const states = Object.entries(s.states).map(([k, v]) => `    ${k}: ${yamlStr(v)}`);
  if (s.trackerKind === 'github_issues') {
    const lines = [
      'tracker:',
      '  kind: github_issues',
      `  repo: ${yamlStr(s.issuesRepo.trim() || s.repo)}`,
      '  credential: { service: github, account: default }',
      `  repo_key: ${yamlStr(s.repoKey)}`,
      `  identifier_prefix: ${yamlStr(s.identifierPrefix)}`,
    ];
    if (s.scopeLabel.trim()) lines.push(`  scope_label: ${yamlStr(s.scopeLabel)}`);
    lines.push('  states:', ...states);
    return lines;
  }
  const lines = [
    'tracker:',
    '  kind: notion',
    `  database_id: ${yamlStr(s.notionDb)}`,
    '  credential: { service: notion, account: default }',
    '  properties:',
    `    status: ${yamlStr(s.statusProp)}`,
    `    identifier: ${yamlStr(s.idProp)}`,
  ];
  if (s.repoProp.trim()) lines.push(`    repo: ${yamlStr(s.repoProp)}`);
  lines.push('  states:', ...states);
  if (s.scopeProp.trim()) lines.push('  scope:', '    type: checkbox', `    property: ${yamlStr(s.scopeProp)}`);
  return lines;
}

/** Build corral.yaml from the wizard state (credentials are refs, not values). */
export function buildConfigYaml(s: WizardState): string {
  return [
    '# Generated by the Corral setup wizard. Secrets live in the keychain / file store.',
    'profile:',
    `  language: ${yamlStr(s.language)}`,
    `  stack: ${yamlStr(s.stack)}`,
    '',
    ...trackerYaml(s),
    '',
    'repositories:',
    '  - kind: github',
    `    key: ${yamlStr(s.repoKey)}`,
    `    repo: ${yamlStr(s.repo)}`,
    '    credential: { service: github, account: default }',
    '    branch_strategy:',
    `      production: ${yamlStr(s.production)}`,
    `      development: ${yamlStr(s.development)}`,
    '',
    'agent:',
    `  provider: ${s.provider}`,
    `  transport: ${s.transport}`,
    `  credential: { service: ${serviceFor(s.provider)}, account: default }`,
    '  models:',
    `    planning: ${yamlStr(s.planningModel)}`,
    `    implementation: ${yamlStr(s.implementationModel)}`,
    '',
    'workspace:',
    `  backend: ${s.backend}`,
    '',
    'channel:',
    '  kind: web',
    `  port: ${s.port}`,
    '',
    `max_active_issues: ${s.maxActive}`,
    '',
  ].join('\n');
}

/** Secrets to persist (service, account, value). Notion token only when using Notion. */
export function secretsFor(s: WizardState): Array<{ service: string; account: string; value: string }> {
  const out = [{ service: 'github', account: 'default', value: s.githubToken }];
  if (s.trackerKind === 'notion') out.push({ service: 'notion', account: 'default', value: s.notionToken });
  if (s.agentKey.trim()) out.push({ service: serviceFor(s.provider), account: 'default', value: s.agentKey });
  return out.filter((x) => x.value.trim());
}
